sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 2.26.1

before_install:
  - docker build -t olkabolkagoryashenko/flask-test -f ./backend/Dockerfile.dev ./backdend


script:
  - docker run -e CI=true olkabolkagoryashenko/flask-test python web.py test

after_script:
  - docker-compose down