version: '3'
services:

  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=flask:5050  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - flask

  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
     - 27017:27017
    #mount volume to our file system
    volumes:
      - ./data/db:/data/db


  
  flask:
    # path to  Dockerfile
    build: ./backend
    # name of the container
    container_name: backend-flask
    # restart the service 
    restart: on-failure
    # mount volume for our Flask app
    stop_signal: SIGINT
    volumes:
      - ./backend:/backend
    depends_on:
      -  mongodb
    # port mapping
    ports:
      - "5050:5050"
    command: python web.py