version: '3'
services:

  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    environment: 
      - FLASK_SERVER_ADDR=flask:5050
      - DOLLAR=$$  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
      - 443:443
    networks:
      - frontnet
    depends_on:
      - flask

  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    expose:
     - 27017
    networks:
      - backnet
    #mount volume to our file system
    volumes:
      - ./../data:/data/db

  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
     - 6379:6379
  
  flask:
    # path to  Dockerfile
    build: ./backend
    # name of the container
    container_name: backend-flask
    # restart the service 
    restart: on-failure
    # mount volume for our Flask app
    stop_signal: SIGINT
    volumes:
      - ./backend:/backend
    depends_on:
      -  mongodb
      -  redis
    # port mapping
    networks:
      - backnet
      - frontnet
    expose:
      - 5050
    command: python web.py
  
networks:
    backnet:
    frontnet:
volumes:
   data: