# Download python 3.9 from dockerhub
FROM python:3.9
RUN python -m pip install --upgrade pip
# Specifying a working directory
WORKDIR /backend
# download & install dependencies
COPY requirements.txt /backend
RUN pip install -r requirements.txt
# copy the directory with Dockerfile, 
# into working directory
COPY . /backend
CMD ["python", "web.py"]