# Download python 3.9 from dockerhub
FROM python:3.9
# Specifying a working directory
WORKDIR /backend
# download & install dependencies
COPY requirements.txt /backend
# copy the directory with Dockerfile, 
# into working directory
COPY . /backend
CMD ["python", "web.py"]